spring:
  application:
    name: CrudApplication

  data:
    mongodb:
      uri: mongodb://localhost:27017/employee_db

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.crudapp: DEBUG

